# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
name:             照片 - 56k 小猫
title:            照片
longtitle:        照片 - 56k 小猫
author:           James Li
email:            i@lishuhang.me
description:       社长的照片日记
url:              'https://56k.lishuhang.me/'
# baseurl:          '/'
rss:              RSS

favicon_path:     /favicon.ico

twitter:     'lishuhang'
github:      'lishuhang'
instagram:   'lishuhang'
facebook:    'lishuhang'
disqus: lishuhang
google_analytics: UA-17809464-2

markdown:  kramdown
permalink: pretty
paginate:  10

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll/tagging
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-mentions
  - jekyll-seo-tag

gems: [jekyll-paginate,pager,pagination]   #添加插件
paginate: 10   #开启分页
paginate_path: "blog/page:num"  #首页分页

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:title/